# uses表示使用一些第三方库

# actions的名称
name: 更新文档到服务器

on:
  push:
    # push 代码的时候，监听该分支的改变
    branches:
      - master

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库 action/checkout获取代码
        uses: actions/checkout@master
      # 安装Node环境
      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@master
        with:
          node-version: lts/*
      # 安装pnpm
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 安装项目依赖
      - name: 安装依赖
        run: pnpm install

      # 项目打包
      - name: 打包
        run: pnpm run docs:build

      # 将打包后的文件上传到服务器
      - name: 发布到服务器
        # https://github.com/easingthemes/ssh-deploy
        uses: easingthemes/ssh-deploy@main
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.BYW_PRIVATE_KEY }}
          # SCP参数
          ARGS: '-avzr --delete'
          # 服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_120 }}
          # 用户
          REMOTE_USER: 'root'
          # 源目录
          SOURCE: '.vitepress/dist/'
          # 目标地址
          TARGET: '/var/www/html/english'
          SCRIPT_BEFORE: 'ls'
